version: '3.9'
services:
  media-backend:
    container_name: media-backend
    image: cleider87/media-api-backend:latest
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: unless-stopped